## Numpy

In [9]:
import numpy as np

## Basic Operation

In [10]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,2])

In [11]:
v1 + v2

array([3, 5, 7])

In [12]:
v2 - v1

array([-1, -1, -3])

In [13]:
v1 * v2

array([ 2,  6, 10])

In [14]:
v2/v1

array([0.5       , 0.66666667, 0.4       ])

## Matrix

In [16]:
# np.one((3,3))
# np.zeros((3,3))
np.random.random((3,3))

array([[0.51402171, 0.21127295, 0.51709864],
       [0.25795995, 0.02705261, 0.92279222],
       [0.58212507, 0.63505861, 0.01096356]])

In [17]:
mat = np.array([
    [1,2]
    ,[3,4]
])

In [18]:
ones = np.ones((2,2))

In [19]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [20]:
mat + np.array([2,3])

array([[3, 5],
       [5, 7]])

In [21]:
mat * mat

array([[ 1,  4],
       [ 9, 16]])

In [22]:
np.matmul(mat,mat)

array([[ 7, 10],
       [15, 22]])