## Numpy

In [1]:
import numpy as np

## Array

Vector : 3i + 2j + 3k --> 1D

Matrix : --> 2D
         
         1 0 1 
         
         1 1 1
         
         0 0 1

In [2]:
a = np.array([3,2,3,5,6])

In [3]:
a

array([3, 2, 3, 5, 6])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0,1,0.02)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [8]:
mylist = [3, 2, 3, 5, 6]

mylist.append([2,3])
mylist[-1]

[2, 3]

In [9]:
np.append(a, [2,3])

array([3, 2, 3, 5, 6, 2, 3])

In [10]:
np.delete(a, [2,4])

array([3, 2, 5])

In [11]:
arr = np.array([10,4,3,19,2,1,6,18])

In [12]:
np.sort(arr)

array([ 1,  2,  3,  4,  6, 10, 18, 19])

## Shape and Size

In [13]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [14]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [16]:
arr.shape

(8,)

In [17]:
arr2.shape

(3, 4)

In [18]:
arr.ndim

1

In [19]:
arr2.ndim

2

In [20]:
arr.size

8

In [21]:
arr2.size

12

## Reshaping Array

In [22]:
print(arr)
print(arr.shape)

[10  4  3 19  2  1  6 18]
(8,)


In [23]:
arr_reshape = arr.reshape(2,4)

In [24]:
arr_reshape.ndim

2

In [25]:
arr.reshape(2,2,2)

array([[[10,  4],
        [ 3, 19]],

       [[ 2,  1],
        [ 6, 18]]])

In [26]:
arr[np.newaxis].shape

(1, 8)

In [27]:
arr.reshape(1,8)

array([[10,  4,  3, 19,  2,  1,  6, 18]])

In [28]:
arr[: , np.newaxis].shape

(8, 1)

In [29]:
np.expand_dims(arr,axis=1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 6],
       [18]])

## Indexing and Slicing

In [30]:
mylist = [1,2,3,4,5,6,7,8]

In [31]:
mylist[1:4]

[2, 3, 4]

In [32]:
mylist[-3]

6

In [33]:
data = np.array([1,2,3,4,5,6,7,8])

In [34]:
data[0]

1

In [35]:
data[1:4]

array([2, 3, 4])

In [36]:
data[-2:]

array([7, 8])

In [37]:
data[data >= 4]

array([4, 5, 6, 7, 8])

In [38]:
data[data%2 == 0]

array([2, 4, 6, 8])

In [39]:
data[(data > 3) & (data%2==0)]

array([4, 6, 8])

In [40]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [41]:
arr1 = arr[:4]
arr2 = arr[4:]

In [42]:
arr1

array([10,  4,  3, 19])

In [43]:
arr2

array([ 2,  1,  6, 18])

In [44]:
np.vstack((arr1,arr2))

array([[10,  4,  3, 19],
       [ 2,  1,  6, 18]])

In [45]:
a1 = np.array([
    [1,1]
    ,[2,2]
])
a2 = np.array([
    [3,3]
    ,[4,4]
])

In [46]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
np.hstack((arr1,arr2))

array([10,  4,  3, 19,  2,  1,  6, 18])

In [48]:
np.hstack((a1,a2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [49]:
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12]
    ,[13,14,15,16,17,18,19,20,21,22,23,24]
])

In [50]:
np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

## Copy Array

In [51]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [52]:
arr2 = arr.copy()

In [53]:
arr2 * 2

array([20,  8,  6, 38,  4,  2, 12, 36])

## Basic Operations

In [54]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,2])

In [55]:
v1 + v2

array([3, 5, 7])

In [56]:
v2 - v1

array([-1, -1, -3])

In [57]:
v1 * v2

array([ 2,  6, 10])

In [58]:
v2/v1

array([0.5       , 0.66666667, 0.4       ])

In [59]:
data.sum()

36

In [60]:
a1

array([[1, 1],
       [2, 2]])

In [61]:
a1.sum(axis=0)

array([3, 3])

In [62]:
v1

array([2, 3, 5])

In [63]:
v1 * 5

array([10, 15, 25])

In [64]:
M = np.arange(0,16).reshape(4,4)

In [65]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
M.max(axis=0)

array([12, 13, 14, 15])

In [67]:
M.min()

0

In [68]:
M.min(axis=1)

array([ 0,  4,  8, 12])

In [69]:
M.min(axis=0)

array([0, 1, 2, 3])

In [70]:
M.std(axis=0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [71]:
M.mean(axis=0)

array([6., 7., 8., 9.])

## Matrix

In [72]:
# np.ones((3,3))
# np.zeros((3,3))
np.random.random((3,3))

array([[0.07984225, 0.62532033, 0.79138882],
       [0.44392003, 0.93887956, 0.80563837],
       [0.75856094, 0.96754865, 0.40305383]])

In [73]:
mat = np.array([
    [1,2]
    ,[3,4]
])

In [74]:
ones = np.ones((2,2))

In [75]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [76]:
mat + 5

array([[6, 7],
       [8, 9]])

mat + np.array([2,3])

In [77]:
mat * mat

array([[ 1,  4],
       [ 9, 16]])

6 10

In [78]:
mat

array([[1, 2],
       [3, 4]])

In [79]:
np.matmul(mat,mat)

array([[ 7, 10],
       [15, 22]])

In [80]:
M = np.random.random((5,5))

In [81]:
M

array([[0.21589012, 0.67433922, 0.62803419, 0.74755341, 0.17890101],
       [0.52759657, 0.31425173, 0.02841648, 0.68418028, 0.83974049],
       [0.53128818, 0.36179695, 0.31225543, 0.4162165 , 0.93257422],
       [0.72123709, 0.50333976, 0.67582448, 0.73989776, 0.15755848],
       [0.22569301, 0.16839034, 0.79954214, 0.65125855, 0.18062431]])

In [82]:
M[2, 1:4]

array([0.36179695, 0.31225543, 0.4162165 ])

In [83]:
M.min(axis=0)

array([0.21589012, 0.16839034, 0.02841648, 0.4162165 , 0.15755848])

In [84]:
np.dot(mat,np.linalg.inv(mat))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [85]:
mat

array([[1, 2],
       [3, 4]])

In [86]:
np.linalg.inv(mat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Solve

x + 2y = 1
3x + 5y = 2

[1 2] [1]
[3 5] [2]


In [87]:
mat_per = np.array([
    [1,2]
    ,[3,5]
])

mat_has = np.array([1,2])

np.linalg.solve(mat_per,mat_has)

array([-1.,  1.])

## Transpose

In [88]:
Mat = np.array([
    [1, 2]
    ,[3,4]
    ,[5,6]
])

In [89]:
Mat.T.shape

(2, 3)

In [90]:
mat_transposed = Mat.T

In [91]:
mat_transposed.reshape(6,1)

array([[1],
       [3],
       [5],
       [2],
       [4],
       [6]])

In [92]:
one_3d = np.random.random((3,3,3))

In [93]:
one_3d.mean()

0.4668158677340768

In [94]:
one_3d.shape

(3, 3, 3)

In [95]:
one_3d.reshape((27,))

array([0.27910939, 0.14286429, 0.91255204, 0.92048327, 0.70848747,
       0.01997107, 0.84223465, 0.04099697, 0.63056611, 0.21064137,
       0.06728402, 0.38002194, 0.26553079, 0.20282245, 0.69214446,
       0.42298826, 0.56099947, 0.89369373, 0.11594415, 0.33107947,
       0.93619601, 0.71443231, 0.18689663, 0.19701039, 0.9709735 ,
       0.06278579, 0.89531846])

In [96]:
one_3d.flatten()

array([0.27910939, 0.14286429, 0.91255204, 0.92048327, 0.70848747,
       0.01997107, 0.84223465, 0.04099697, 0.63056611, 0.21064137,
       0.06728402, 0.38002194, 0.26553079, 0.20282245, 0.69214446,
       0.42298826, 0.56099947, 0.89369373, 0.11594415, 0.33107947,
       0.93619601, 0.71443231, 0.18689663, 0.19701039, 0.9709735 ,
       0.06278579, 0.89531846])

In [97]:
data_aktual = np.random.random(100)

In [98]:
data_prediksi = np.random.random(100)

In [99]:
(1/len(data_aktual)) * np.sum(np.square(data_aktual - data_prediksi))

0.14916393036282394

Sesi 4
